syncfusion-content/xamarin-docs

Xamarin/Pdf-Viewer/Supported-and-Unsupported-features.md

Create supported and unsupported features list page in xamarin forms UG.

XAMARIN-42374 : Updated supported and unsupported features list page

---

Xamarin/Pdf-Viewer/Getting-Started.md

XAMARIN-42574-Added corrections in Getting-Started.md.

XAMARIN-42574-Added corrections in Getting-Started.md.

---

Xamarin/Diagram/Connector.md
Xamarin/Diagram/Diagram.md
Xamarin/Diagram/Layout.md
Xamarin/Diagram/Node.md
Xamarin/Diagram/Stencil.md

XAMARIN-42551 Need to include missing API's in UG Diagram control.
Hi Team,
Need to include missing API'in UG Diagram control. Kindly review the changes and let me know your feedback.
With Regards,
Hemalatha D.

XAMARIN-42551 Need to include missing API's in UG Diagram control.

---

Xamarin/Pdf-Viewer/Getting-Started.md

XAMARIN-42575-Added a topic to illustrate how to load a document from URL in Getting Started page

XAMARIN-42575-Add a topic to illustrate how to load a document from URL in Getting Started page

---

Xamarin/Pdf-Viewer/FreeText-Annotation.md
Xamarin/Pdf-Viewer/Working-with-PDF-Coordinates.md
Xamarin/Pdf-Viewer/Working-with-custom-stamp-annotations.md

Hi @ramkumarsync ,
Please find the UG content for the 2022 Volume 1 features and enhancements.
Regards,
Ashok Kumar Viswanathan.

XAMARIN-42829 : Add or update UG documentation for the 2022 Volume 1 features and enhancements

---

Xamarin/DatePicker/Formatting.md

The New format such as dd/MM , MM/yyyy, MMM/yyyy were added In the UG documents on Mar-21-2022

Xamarin-42683-datePicker-ug-update-latest

---

Xamarin/StepProgressBar/Description.md

Hi Team,
To include sample with code snippet for step view with image customisation in Step Progressbar control. Kindly review the changes and let me know your feedback.
With Regards,
Hemalatha D.

XAMARIN-42813 Need to include sample with code snippet for step view with image customization in Step Progressbar 

---

Xamarin/StepProgressBar/BindableLayout.md

Hi Team,
Prepared content for ItemSource with ItemTemplate in Step Progressbar in code behind. Kindly review the changes and provide your feedback.
With Regards,
Gayathri R

XAMARIN-43198-How to set ItemSource with ItemTemplate in Step Progressbar

---

Xamarin/Charts/how-to/Adding-duplicate-axis-in-SfChart.md

Added xaml code in the how to add additional axes in the SfChart ug document.

XAMARIN-43227-Added xaml code in how to add additional axes in ug document.

---

Xamarin/Chat/Suggestions.md

XAMARIN-42675 : Need to update code snippet SfChat Suggestion

XAMARIN-42675 : Need to update code snippet SfChat Suggestion

---

Xamarin/ComboBox/Customizing-ComboBox.md

Adding note in Customizing ComboBox section under SFComboBox

XAMARIN-43325: Update Customizing-ComboBox.md

---

Xamarin/ComboBox/Customizing-ComboBox.md

Adding note in Customizing ComboBox section under SFComboBox

XAMARIN-43325: Add Note In SfComboBox

---

Xamarin/Rich-Text-Editor/Basic-Features.md

Hi Team,
I have added the content for font name usability feature and Style Sheet Feature with code snippets . Kindly review the changes and let me know your feedback.
With Regards,
Benin JS

XAMARIN-43417-Need to prepare UG content for fontname Usability Feature

---

Xamarin/Pdf-Viewer/FreeText-Annotation.md
Xamarin/Pdf-Viewer/Getting-Started.md
Xamarin/Pdf-Viewer/Shape-Annotation.md
Xamarin/Pdf-Viewer/TextMarkup.md

Publish UG documentation for 2022 Vol 2 features.
* Polyline 
* Squiggly
* Locked annotation selection colour changes
* Restrict popup from being rendered as free text annotation

XAMARIN-43463 :  Publish UG documentation for 2022 Vol 2 features

---

Xamarin/Rich-Text-Editor/Basic-Features.md
Xamarin/Rich-Text-Editor/Customization.md

Hi team,
Modified the UG content 
Regards
Benin JS

XAMARIN-43415-Need to prepare UG content for StyleSheetType API in RichTextEditor control

---

Xamarin/Installation/mac-installer/how-to-install.md
xamarin-toc.html

IN-18200-UG-Documentation-xamarin-hotfix

---

Xamarin/Chips/DataTemplateSelector.md

Worked on site audit issues, merge these changes,
Regards,
Gowthaman

SEO-2370_Site_Audit_Issues

---

Xamarin/Range-Slider/How-To.md

Worked on site audit Missing h1 tags issues, merge these changes,
Regards,
Gowthaman

SEO-2423_Site_Audit_Issues

---

Xamarin/Diagram/Getting-Started.md
Xamarin/Diagram/OverviewPanel.md

Hi team, 
I have added content for Density Calculations for android and iOS
Regards
Benin JS

XAMARIN-43501-Need to create Density calculation UG document

---

Xamarin/Numeric-Entry/Return-type.md

Hi @vigneshrameshsync ,
I have modified the content. Please review the content and let me know if you have any other concerns.
Regards,
@EswaranSyncfusion

XAMARIN-43633 Need to add implementation of ReturnCommandParameter in SfNumericTextBox

---

Xamarin/Radio-Button/Event.md
Xamarin/Radio-Button/Getting-Started.md
Xamarin/Radio-Button/Grouping.md
Xamarin/Radio-Button/Visual-Customization.md

Linking all fields, properties and events to SfRadioButton

XAMARIN-43636 : Linking all fields, properties and events to SfRadioButton

---

Xamarin/Badge-View/Animation.md
Xamarin/Badge-View/Overview.md

Worked on site audit issues, merge these changes,
Regards,
Gowthaman

SEO-2475_Site_Audit_Issues

---

Xamarin/CheckBox/Visual-Customization.md

Linking all fields, properties and events to SfCheckBox

XAMARIN-43636 : Linking all fields, properties and events to SfCheckBox

---

Xamarin/Chips/Customization.md
Xamarin/Chips/Events.md
Xamarin/Chips/Getting-Started.md
Xamarin/Chips/Populating-chips-item.md
Xamarin/Chips/Types.md

Linking all fields, properties and events to SfChip and SfChipGroup

XAMARIN-43636 : Linking all fields, properties and events to SfChip and SfChipGroup

---

Xamarin/Button/Customization.md

Linking all fields, properties and events to SfButtons

XAMARIN-43636 : Linking all fields, properties and events to SfButtons

---

Xamarin/SignaturePad/Customization.md
Xamarin/SignaturePad/Events.md
Xamarin/SignaturePad/Getting-Started.md

Linking all fields, properties and events to SfSiganturePad

XAMARIN-43636 : Linking all fields, properties and events to SfSiganturePad

---

Xamarin/Segmented-Control/Customization.md
Xamarin/Segmented-Control/Dealing-with-selection-changed.md
Xamarin/Segmented-Control/Getting-Started.md
Xamarin/Segmented-Control/Handling-multiple-segments.md
Xamarin/Segmented-Control/Indicating-the-selected-item.md

Linking all fields, properties and events to SfSegmentedControl

XAMARIN-43636 : Linking all fields, properties and events to SfSegmentedControl

---

Xamarin/DatePicker/Customizations.md
Xamarin/DatePicker/Date-Restriction.md
Xamarin/DatePicker/Events.md
Xamarin/DatePicker/Formatting.md
Xamarin/DatePicker/Looping.md
Xamarin/DatePicker/gettingstarted.md

Linking all fields, properties and events to SfDatePicker

XAMARIN-43636 : Linking all fields, properties and events to SfDatePicker

---

Xamarin/Range-Slider/Accessibility.md
Xamarin/Range-Slider/Formatting-String.md
Xamarin/Range-Slider/Getting-Started.md
Xamarin/Range-Slider/How-To.md
Xamarin/Range-Slider/Labels-Customization.md
Xamarin/Range-Slider/Orientation.md
Xamarin/Range-Slider/Range.md
Xamarin/Range-Slider/Selection-Value-Configuration.md
Xamarin/Range-Slider/Ticks-Customization.md
Xamarin/Range-Slider/ToolTip-Support.md
Xamarin/Range-Slider/Track-Bar-Customization.md

Linking all fields, properties and events to SfRangeSlider

XAMARIN-43636 : Linking all fields, properties and events to SfRangeSlider

---

Xamarin/Rotator/Accessibility.md
Xamarin/Rotator/Adding-Looping-and-Delays.md
Xamarin/Rotator/DataTemplateSelector.md
Xamarin/Rotator/Dots-Customization.md
Xamarin/Rotator/Events.md
Xamarin/Rotator/Header-Visibility.md
Xamarin/Rotator/Loading-Online-Images.md
Xamarin/Rotator/Navigation-Modes.md
Xamarin/Rotator/Placement-Modes.md
Xamarin/Rotator/Populating-Data.md
Xamarin/Rotator/Sliding-Direction.md
Xamarin/Rotator/getting-started.md
Xamarin/Rotator/overview.md

Linking all fields, properties and events to SfRotator

XAMARIN-43636 : Linking all fields, properties and events to SfRotator

---

Xamarin/Tabbed-View/Accessibility.md
Xamarin/Tabbed-View/CenterButtonSettings.md
Xamarin/Tabbed-View/Display-Type.md
Xamarin/Tabbed-View/Getting-Started.md
Xamarin/Tabbed-View/NestedTab.md
Xamarin/Tabbed-View/Swiping.md
Xamarin/Tabbed-View/TabItem-Customization.md
Xamarin/Tabbed-View/TabView-events.md
Xamarin/Tabbed-View/TabViewHeaderCustomization.md

Linking all fields, properties and events to SfTabView

XAMARIN-43636 : Linking all fields, properties and events to SfTabView

---

Xamarin/ComboBox/Accessibility.md
Xamarin/ComboBox/AutoSizing.md
Xamarin/ComboBox/ComboBox-Filtering-Options.md
Xamarin/ComboBox/Customizing-ComboBox.md
Xamarin/ComboBox/DataTemplateSelector.md
Xamarin/ComboBox/Dealing-with-Suggestion-Box.md
Xamarin/ComboBox/Editable-Modes.md
Xamarin/ComboBox/Events.md
Xamarin/ComboBox/Getting-Started.md
Xamarin/ComboBox/Header-and-Footer.md
Xamarin/ComboBox/Highlighting-matched-text.md
Xamarin/ComboBox/Maximum-display-item-with-Expander.md
Xamarin/ComboBox/Multiple-selection.md
Xamarin/ComboBox/No-Result-Found.md
Xamarin/ComboBox/Populating-Data.md
Xamarin/ComboBox/Retrieving-Selected-Values.md
Xamarin/ComboBox/Right-to-left.md

Linking all fields, properties and events to SfComboBox

XAMARIN-43636 : Linking all fields, properties and events to SfComboBox

---

Xamarin/Navigation-Drawer/Accessibility.md
Xamarin/Navigation-Drawer/Duration.md
Xamarin/Navigation-Drawer/Getting-Started.md
Xamarin/Navigation-Drawer/Main-Content.md
Xamarin/Navigation-Drawer/Multi-drawer.md
Xamarin/Navigation-Drawer/Navigation-Pane-Sides.md
Xamarin/Navigation-Drawer/Side-Pane-Content.md
Xamarin/Navigation-Drawer/Side-Pane-Sizing.md
Xamarin/Navigation-Drawer/Swipe-Gesture-and-Sensitivity.md
Xamarin/Navigation-Drawer/Toggle-Animations.md
Xamarin/Navigation-Drawer/Toggling-Drawer.md

Linking all fields, properties and events to SfNavigationDrawer

XAMARIN-43636 : Linking all fields, properties and events to SfNavigationDrawer

---

Xamarin/AutoComplete/Accessibility.md
Xamarin/AutoComplete/AutoComplete-Filtering-Options.md
Xamarin/AutoComplete/AutoComplete-Modes.md
Xamarin/AutoComplete/AutoSizing.md
Xamarin/AutoComplete/Customizing-AutoComplete.md
Xamarin/AutoComplete/DataTemplateSelector.md
Xamarin/AutoComplete/Dealing-with-Suggestion-Box.md
Xamarin/AutoComplete/Diacritic-Sensitivity.md
Xamarin/AutoComplete/Getting-Started.md
Xamarin/AutoComplete/Header-and-Footer.md
Xamarin/AutoComplete/Highlighting-matched-text.md
Xamarin/AutoComplete/Maximum-display-item-with-Expander.md
Xamarin/AutoComplete/Multiple-selection.md
Xamarin/AutoComplete/No-Result-Found.md
Xamarin/AutoComplete/Populating-Data.md
Xamarin/AutoComplete/Prefix-Characters-Constraint.md
Xamarin/AutoComplete/Retrieving-Selected-Values.md
Xamarin/AutoComplete/Watermark.md
Xamarin/AutoComplete/how-to.md

Linking all fields, properties and events to SfAutoComplete

XAMARIN-43636 : Linking all fields, properties and events to SfAutoComplete

---

Xamarin/Picker/Accessibility.md
Xamarin/Picker/Events.md
Xamarin/Picker/Looping.md
Xamarin/Picker/cascading.md
Xamarin/Picker/datatemplateselector.md
Xamarin/Picker/datepicker.md
Xamarin/Picker/datetimepicker.md
Xamarin/Picker/dealingwithcolumns.md
Xamarin/Picker/dealingwithheaderandfooter.md
Xamarin/Picker/gettingstarted.md
Xamarin/Picker/populatingitems.md
Xamarin/Picker/timepicker.md

Linking all fields, properties and events to SfPicker

XAMARIN-43636 : Linking all fields, properties and events to SfPicker

---

Xamarin/Radio-Button/Event.md
Xamarin/Radio-Button/Getting-Started.md
Xamarin/Radio-Button/Grouping.md
Xamarin/Radio-Button/Visual-Customization.md

Editted The Linking Of Properties, Methods and Events in SfRadioButton

XAMARIN-43636-Editted The Linking Of Properties, Methods and Events in SfRadioButton

---

Xamarin/CheckBox/Getting-Started.md
Xamarin/CheckBox/Visual-Customization.md

Edited The Linking Of Properties, Methods and Events in SfCheckBox

XAMARIN-43636 : Edited The Linking Of Properties, Methods and Events in SfCheckBox

---

Xamarin/Chips/Customization.md
Xamarin/Chips/DataTemplateSelector.md
Xamarin/Chips/Events.md
Xamarin/Chips/Getting-Started.md

Edited The Linking Of Properties, Methods and Events in SfChip and SfChipGroup

XAMARIN-43636 : Edited The Linking Of Properties, Methods and Events in SfChip and SfChipGroup

---

Xamarin/Button/Customization.md
Xamarin/Button/GettingStarted.md
Xamarin/Button/VisualStates.md

Edited The Linking Of Properties, Methods and Events in SfButtons

XAMARIN-43636 : Edited The Linking Of Properties, Methods and Events in SfButtons

---

Xamarin/SignaturePad/Events.md

Edited The Linking Of Properties, Methods and Events in SfSignaturePad

XAMARIN-43636 : Edited The Linking Of Properties, Methods and Events in SfSignaturePad

---

Xamarin/DatePicker/Customizations.md
Xamarin/DatePicker/gettingstarted.md
Xamarin/DatePicker/how-to/How-to-get-selected-date.md
Xamarin/DatePicker/how-to/How-to-show-a-dialogmode.md

Editted The Linking Of Properties, Methods and Events in SfDatePicker

XAMARIN-43636-Editted The Linking Of Properties, Methods and Events in SfDatePicker

---

Xamarin/Rotator/Accessibility.md
Xamarin/Rotator/Events.md
Xamarin/Rotator/Placement-Modes.md
Xamarin/Rotator/Populating-Data.md
Xamarin/Rotator/getting-started.md

Editted The Linking Of Properties, Methods and Events  in SfRotator

XAMARIN-43636 :Editted The Linking Of Properties, Methods and Events  in SfRotator

---

Xamarin/Busy-Indicator/Getting-Started.md
Xamarin/Busy-Indicator/Set-Header.md

Edited The Linking Of Properties, Methods and Events  in SfBusyIndicator

XAMARIN-43636 :Edited The Linking Of Properties, Methods and Events  in SfBusyIndicator

---

Xamarin/Navigation-Drawer/Getting-Started.md
Xamarin/Navigation-Drawer/Multi-drawer.md
Xamarin/Navigation-Drawer/Toggling-Drawer.md

Edited The Linking Of Properties, Methods and Events in SfNavigationDrawer

XAMARIN-43636 : Edited The Linking Of Properties, Methods and Events in SfNavigationDrawer

---

Xamarin/ComboBox/Dealing-with-Suggestion-Box.md
Xamarin/ComboBox/Events.md
Xamarin/ComboBox/Getting-Started.md
Xamarin/ComboBox/Highlighting-matched-text.md
Xamarin/ComboBox/Populating-Data.md
Xamarin/ComboBox/Retrieving-Selected-Values.md

Edited The Linking Of Properties, Methods and Events in SfComboBox

XAMARIN-43636 :Edited The Linking Of Properties, Methods and Events in SfComboBox

---

Xamarin/AutoComplete/Dealing-with-Suggestion-Box.md
Xamarin/AutoComplete/Getting-Started.md
Xamarin/AutoComplete/Maximum-display-item-with-Expander.md
Xamarin/AutoComplete/Populating-Data.md
Xamarin/AutoComplete/Retrieving-Selected-Values.md

Edited The Linking Of Properties, Methods and Events in SfAutoComplete

XAMARIN-43636 :Edited The Linking Of Properties, Methods and Events in SfAutoComplete

---

Xamarin/Tabbed-View/CenterButtonSettings.md
Xamarin/Tabbed-View/TabViewHeaderCustomization.md

Edited The Linking Of Properties, Methods and Events in SfTabView

XAMARIN-43636-Editted The Linking Of Properties, Methods and Events in SfTabView

---

Xamarin/TimePicker/Customizations.md
Xamarin/TimePicker/Events.md
Xamarin/TimePicker/Formatting.md
Xamarin/TimePicker/How-To.md
Xamarin/TimePicker/Looping.md
Xamarin/TimePicker/gettingstarted.md

Linking all fields, properties and events to SfTimePicker

XAMARIN-43636 : Linking all fields, properties and events to SfTimePicker

---

Xamarin/Rating/Accessibility.md
Xamarin/Rating/Add-Custom-Items.md
Xamarin/Rating/Appearance-Customization.md
Xamarin/Rating/Appearance-and-Styling.md
Xamarin/Rating/Getting-Started.md
Xamarin/Rating/Overview.md
Xamarin/Rating/Precision-Mode.md
Xamarin/Rating/Restrict-User-Selection.md
Xamarin/Rating/ToolTip.md
Xamarin/Rating/View-Range-Selection.md

Linking all fields, properties and events to SfRating

XAMARIN-43636 : Linking all fields, properties and events to SfRating

---

Xamarin/Picker/Localization.md
Xamarin/Picker/dealingwithcolumns.md
Xamarin/Picker/gettingstarted.md

Editted The Linking Of Properties, Methods and Events in SfPicker

XAMARIN-43636 :Editted The Linking Of Properties, Methods and Events in SfPicker

---

Xamarin/Avatar-view/Content-type.md
Xamarin/Avatar-view/Getting-Started.md
Xamarin/Avatar-view/Overview.md
Xamarin/Avatar-view/customization.md
Xamarin/Avatar-view/how-to.md
Xamarin/Avatar-view/visualstyles.md

Linking all fields, properties and events to SfAvatarView

XAMARIN-43636 : Linking all fields, properties and events to SfAvatarView

---

Xamarin/Switch/Accessibility.md
Xamarin/Switch/customization.md
Xamarin/Switch/gettingstarted.md
Xamarin/Switch/how-to.md
Xamarin/Switch/orientation.md
Xamarin/Switch/overview.md
Xamarin/Switch/states.md
Xamarin/Switch/visualtypes.md

Linking Properties, Methods and Events to SfSwitch

XAMARIN-43636 - Linking Properties, Methods and Events to SfSwitch

---

Xamarin/Scheduler/data-bindings.md

WPF-61857-add the UG documentation for TextColor

WPF-61857-add the UG documentation for TextColor

---

Xamarin/DataGrid/Swiping.md
Xamarin/ListView/MVVM.md
Xamarin/Popup/Popup-positioning.md

Resolved the indentation issues with UG documentation

XAMARIN-44046 : Resolve indentation issues with UG documentation

---

Xamarin/Calendar/Getting-Started.md
Xamarin/DataForm/Editors.md
Xamarin/Kanban-Board/Localization.md

XAMARIN-43999-Modified the code snippet alignment

XAMARIN-43999-Modified the code snippet alignment

---

Xamarin/Masked-Entry/events.md
Xamarin/Masked-Entry/visual-customization.md

Hi @ChristoIssac,
|Task Category| Pages With Redirect - Search console|
|:--|:--|
|Issue count| Help site links - 1000 |
|Fixed Count| Help site links - 30 |
|Analysis| Inspecting the links and found referring pages |
|Solution| replaced the exact URL instead of old URL |
|Hotfix PR| https://github.com/syncfusion-content/xamarin-docs/pull/362 | 
|Task link|https://syncfusion.atlassian.net/browse/SEO-2684|
|Excel| N/A |
Regards,
Gowthaman

SEO-2684-Coverage-Page-With-Redirect-UG

---

Xamarin/Maps/How-To/Transform-latitude-and-longitude-value-to-pixel-value-and-vice-versa.md

Hi @Aishwarya-Ganesan 
Please review the multiple H1 changes for Angular Diagram.
Regards,
Beryl.

SEO-2748-Xamarin

---

Xamarin/Circular-Gauge/Getting-Started.md
Xamarin/ComboBox/Populating-Data.md
Xamarin/DataGrid/Getting-started.md
Xamarin/ListView/Getting-started.md
Xamarin/Numeric-Entry/Getting-Started.md
Xamarin/Scheduler/getting-started.md
Xamarin/Segmented-Control/Getting-Started.md

Hi @ChristoIssac,
|Task Category| Pages With Redirect - Search console|
|:--|:--|
|Issue count| Help site links - 1000 |
|Fixed Count| Help site links - 7 |
|Analysis| Inspecting the links and found referring pages |
|Solution| replaced the exact URL instead of old URL |
|Hotfix PR| https://github.com/syncfusion-content/xamarin-docs/pull/373 | 
|Task link|https://syncfusion.atlassian.net/browse/SEO-2684|
|Excel| N/A |
Regards,
Gowthaman

SEO-2684-Coverage-report-pages-with-redirect

---

Xamarin/Introduction/xamarin-cross-platform-ui.md

Hi Team,
I have modified the RichTextEditor navigation link. Kindly review and update your suggestion.
Regards,
Hemalatha D.

XAMARIN-44255 Need to update proper link in Xamarin documentation RichTextEditor control

---

Xamarin/Charts/Localization.md

Update bullet instead of numbers used on the chart localization file.

WINUI-3166 Resolved indention related issues in the chart localization file

---

Xamarin/Cards/Getting-Started.md

Hi @sheiksyedm ,
The wrong weblink is removed and added the correct link. So could you please review the content changes and let me know if you have any other concerns.
Regards,
Eswaran

XAMARIN-44377 Need to add proper weblinks in the SfCardLayout Control

---

Xamarin/Rich-Text-Editor/Basic-Features.md

Hi Team,
Prepared UG for volume 4 promised feature. Kindly review it and provide your feedback.
With Regards,
Gayathri R

XAMARIN-44314-Prepared UG content for volume 4 promised feature

---

Xamarin/Popup/Popup-positioning.md

XAMARIN-44440 : Fixed the UG failure Error

---

Xamarin/Introduction/xamarin-cross-platform-ui.md

XAMARIN-44479-Change the UG error in xamarin forms

XAMARIN-44479-Change the UG error in xamarin forms

---

Xamarin/Charts/Getting-Started.md
Xamarin/Charts/chartseries.md
Xamarin/Pull-To-Refresh/customization.md

Hi Aishwarya,
Worked on page with redirect for help links, so merge these changes
Regards,
Gowthaman

SEO-3146-coverage-page-with-redirect-help

---

Xamarin/Backdrop-Page/CornerShape-Customization.md

Please review the changes for Page with redirect for Xamarin
Regards,
Yvone.

SEO-3239 Xamarin Page with redirect

---

Xamarin/Popup/Layout-Customizations.md

Change content in SfPopup Layout Customization

XAMARIN-44669 : UG change in SfPopup

---

Xamarin/Upgrade/how-to-upgrade.md

Please review changes for Xamarin docs.
Regards,
Sharly A.

SEO-3226 - Xamarin docs changes

---

Xamarin/Installation/install-nuget-packages.md

Hi, I have worked on the links with redirects.
Regards,
Beryl.

SEO-3283-Link-With-Redirect-Xamarin

---

Xamarin/Visual-Studio-Integration/Create-Project.md

Updated redirect link for Xamarin
Regards,
Sharly A.

SEO-3446 - Xamarin redirect link

---

Xamarin/DataGrid/Column-Types.md
Xamarin/Scheduler/data-bindings.md

Added redirect links for Xamarin.
Regards,
Sharly A.

SEO-3446 - Xamarin redirect links

---

Xamarin/DataForm/Getting-Started.md
Xamarin/DataGrid/Grouping.md
Xamarin/Popup/Popup-Events.md

Hi 
I worked on the links with redirects,
Regards,
Beryl.

SEO-3458-Links-With-Redirects-Xamarin

---

Xamarin/Pdf-Viewer/Working-with-PDF-AcroForms.md

Hi Team,
Have fixed the issue "invalid byte sequence in UTF-8"

Xamarin-44642- invalid byte sequence in UTF-8

---

Xamarin/DataGrid/Row-Height-Customization.md
Xamarin/ListView/Filtering.md

Hi @gowthamanthavasiyappan,
Please find changes made.
Regards,
Scholar.

SEO-3550 Xamarin changes

---

Xamarin/DateTime-Range-Navigator/Localization.md

Worked on Bing report issues, so merge these changes
Regards,
Gowthaman

SEO-3615-bing-issues

---

Xamarin/DataGrid/Sorting.md
Xamarin/Radio-Button/Getting-Started.md
Xamarin/Range-Slider/Getting-Started.md

Have changed help page with redirect links in Xamarin.
Regards,
Yvone.

SEO-171350 Xamarin Page with redirect links

---

Xamarin/Image-Editor/shapes.md

Hi @Jeyasri-Murugan
I have fixed the alignment issue in the ImageEditor UG. The root cause of the issue was the H3 topic was added before H2 topic. Hence the alignment issue occurred.
Please review this and let me know of any concerns.
Regards,
Muniappan S

826460- Image editor shape ug updated

---

Xamarin/Image-Editor/shapes.md

Hi @Jeyasri-Murugan
I have fixed the alignment issue in the ImageEditor UG. The root cause of the issue was the H3 topic was added before H2 topic. Hence the alignment issue occurred.
Please review this and let me know of any concerns.
Regards,
Muniappan S

826460- Image editor shape ug updated 

---

Xamarin/AutoComplete/Getting-Started.md
Xamarin/Barcode/Getting-Started.md
Xamarin/Calendar/Feature-Comparison-across-the-different-platforms.md
Xamarin/Maps/Legend.md

Please review the changes for Xamarin Page with redirect.
Regards,
Selline Rita.

SEO-3560 - Xamarin Page With Redirect

---

Xamarin/Charts/Localization.md
Xamarin/DataForm/Editing.md
Xamarin/DataGrid/Getting-started.md
Xamarin/Popup/Accessibility.md
Xamarin/Text-Input-Layout/Getting-Started.md

Have made the changes in redirect links. Please review.
Thanks.
Regards,
Edith.

SEO-171754- xamarin controls

---

Xamarin/ListView/Getting-started.md

XF-756347 : Update Getting-started.md

---

Xamarin/ListView/Filtering.md
Xamarin/Numeric-Entry/Colors.md
Xamarin/Rich-Text-Editor/GettingStarted.md
Xamarin/Shimmer/Getting-Started.md
Xamarin/TreeView/Selection.md

Hi @gowthamanthavasiyappan ,
Have worked on changing redirect links in Xamarin.
Regards,
Yvone.

SEO-172160 Xamarin Redirect

---

Xamarin/Pdf-Viewer/Getting-Started.md
Xamarin/Pdf-Viewer/Ink.md
Xamarin/Pdf-Viewer/TextMarkup.md

827622: Publish UG documentation for 2023 Vol 1 SP and Vol2 features

827622: Publish UG documentation for 2023 Vol 1 SP and Vol2 features

---

Xamarin/Barcode/barcode-customization.md

Hi All,
I have added the feature "Create QR code with logo" with code example in SfBarcode UG documentation. Kindly review this and merge.
Regards,
Sowmiya L

832670 - Update the feature "Create QR code with logo" in SfBarcode - Hotfix

---

Xamarin/DataGrid/Data-Binding.md
Xamarin/NumericUpDown/Spin-Button-Customization.md

Xamarin Page With Redirect.
https://github.com/syncfusion-content/xamarin-docs/pull/543

SEO-71714 - Xamarin Page With Redirect

---

Xamarin/Busy-Indicator/Getting-Started.md
Xamarin/Button/VisualStates.md
Xamarin/Charts/Getting-Started.md
Xamarin/ListView/Layouts.md
Xamarin/ListView/Swiping.md

Hello,
I have worked on the links with redirects.
Regards,
Beryl.

SEO-173794-Pages-With-Redirects

---

Xamarin/Expander/Getting-Started.md
Xamarin/Image-Editor/Getting-Started.md
Xamarin/ListView/Item-Size-Customization.md
Xamarin/ListView/Layouts.md
Xamarin/ListView/Swiping.md

Hello,
I have worked on the links with redirects.
Regards,
Beryl.

SEO-173794-Pages-With-Redirects-Xamarin

---

Xamarin/Button/GettingStarted.md
Xamarin/Calendar/Getting-Started.md
Xamarin/DataGrid/Getting-started.md
Xamarin/DataGrid/Grid-Events.md
Xamarin/Diagram/Getting-Started.md
Xamarin/Image-Editor/Getting-Started.md
Xamarin/Navigation-Drawer/Getting-Started.md
Xamarin/Text-Input-Layout/Supported-input-views.md

Have change Xamarin Page with Redirect UG links, please review.
Regards,
Yvone.

SEO-174775 Xamarin Redirect Links

---

Xamarin/Border/Getting-started.md
Xamarin/Charts/working-with-data.md
Xamarin/DataGrid/Summary.md
Xamarin/DataGrid/Unbound-Column.md
Xamarin/ListView/Right-To-Left.md
Xamarin/Radio-Button/Visual-Customization.md
Xamarin/Range-Slider/Getting-Started.md
Xamarin/Shimmer/Getting-Started.md
Xamarin/Switch/gettingstarted.md
Xamarin/Text-Input-Layout/How-to.md

Have worked on changing Page with Redirect links.
Regards,
Yvone.

SEO-174775 Xamarin Page Redirect

---

Xamarin/Charts/Getting-Started.md
Xamarin/Charts/axis.md
Xamarin/DataGrid/Editing.md
Xamarin/DataGrid/Getting-started.md
Xamarin/DataGrid/Swiping.md
Xamarin/DataSource/DataSource-GettingStarted.md
Xamarin/Digital-Gauge/Getting-Started.md
Xamarin/Licensing/overview.md
Xamarin/Radial-Menu/Getting-Started.md
Xamarin/Scheduler/date-navigations.md

Have worked on changing Page with Redirect links.
Regards,
Yvone.

SEO-174775 Xamarin Redirect

---

Xamarin/ComboBox/Dealing-with-Suggestion-Box.md

Hi Team,
I have added GitHub sample link for SfComboBox with Filter options. Kindly review and merge the same.

Added the GitHub sample link for combobox.

---

Xamarin/Rich-Text-Editor/Customization.md

Rich Text Editor provides support to IsScrollButtonVisible feature

843754 Rich Text Editor provides support to IsScrollButtonVisible feature

---

xamarin-toc.html

Hi all,
- With this PR, we have modified the DocIO & Presentation controls direct links in Xamarin platform UG.
- Removed pages other than Overview and Getting Started.
Regards,
Dharanitharan A

ES-846833-Modified DocIO & Presentation controls direct links in Xamarin platform UG-hotfix

---

Xamarin/AutoComplete/Getting-Started.md
Xamarin/DataSource/DataSource-GettingStarted.md
Xamarin/ListView/Getting-started.md
Xamarin/Text-Input-Layout/Container-Type.md

In this PR I have Worked on a page with redirect in Xamarin docs.

SEO-174304 - Xamarin page with redirect

---

Xamarin/Introduction/xamarin-cross-platform-ui.md

Hi @Aishwarya-Ganesan
Corrected the page not found links in this help page. Please check and merge the same.
Thanks,
Mallika

SEO-175881: Page Not Found UG link - fix 

---

Xamarin/Maps/How-To/Load-stream-to-ShapeFileLayer.md
Xamarin/Parallax-View/custom-controls.md

Hello, 
I have worked on the missing H1.
Regards,
Beryl.

SEO-174767-Xamarin-Missing-H1

---

Xamarin/AutoComplete/Getting-Started.md
Xamarin/Charts/how-to/Customize-the-SfChart-padding.md
Xamarin/CheckBox/Getting-Started.md
Xamarin/Circular-Gauge/rim.md
Xamarin/ListView/Grouping.md
Xamarin/Numeric-Entry/Font-Settings.md
Xamarin/Radio-Button/Grouping.md
Xamarin/Scheduler/headers.md
Xamarin/Segmented-Control/Getting-Started.md
Xamarin/Text-Input-Layout/Assistive-Labels.md

Have changed Xamarin Page with Redirect UG.
Regards,
Yvone.

SEO-175659 Xamarin Page with Redirect

---

Xamarin/Picker/gettingstarted.md

Have changed Xamarin Page with Redirect UG.
Regards,
Yvone.

SEO-175659 Xamarin Redirect links

---

Xamarin/Charts/chartseries.md

**Description**
Updated Chart series related kb links in Xamarin UG document
Referred
https://github.com/syncfusion-content/xamarin-docs/pull/667

Xamarin-851315-Update-kb-link-in-Xamarin-UG-document

---

xamarin-toc.html

Hi All,
Modify the TOC file for DocIo and Presentation Product.
Task Link: https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/851567
Regards
venkatesh

ES-851567 Modify TOC File

---

Xamarin/Button/Customization.md
Xamarin/Charts/charttypes.md
Xamarin/Charts/export.md
Xamarin/DataGrid/Export-To-Excel.md
Xamarin/Image-Editor/Text.md
Xamarin/Masked-Entry/events.md
Xamarin/Rating/Getting-Started.md
Xamarin/Scheduler/data-bindings.md
Xamarin/TreeView/Selection.md
Xamarin/Visual-Studio-Integration/Essential-UI-Kit.md

Have changed page with redirect links.
Regards,
Yvone.

SEO-176116 Xamarin Redirect

---

xamarin-toc.html

I have added XlsIO control UG redirect links.

854120 - XlsIOChanges - Xamarin

---

Xamarin/Installation/web-installer/how-to-download.md
Xamarin/Installation/web-installer/how-to-install.md
Xamarin/System-Requirements.md
Xamarin/Upgrade/upgrade-syncfusion-xamarin-nuget-packages.md

Have made changes on the redirect links. Please review.
Thanks.
Regards,
Edith.

SEO-176062-xamarin-UG-page-with-redirect

---

Xamarin/Effects-View/Customization.md
Xamarin/Expander/Accessibility.md
Xamarin/Kanban-Board/Cards.md
Xamarin/Picker/dealingwithcolumns.md
Xamarin/Picker/populatingitems.md
Xamarin/Popup/Localization.md
Xamarin/Popup/getting-started.md
Xamarin/ProgressBar/GettingStarted.md
Xamarin/Pull-To-Refresh/getting-started.md
Xamarin/Radio-Button/Event.md

Hello, 
I have worked on the links with redirects.
Regards,
Beryl.

SEO-176113-Xamarin-Page-With-Redirect4

---

Xamarin/Numeric-Entry/Return-type.md
Xamarin/NumericUpDown/Colors.md
Xamarin/NumericUpDown/Customization.md
Xamarin/NumericUpDown/Font-Settings.md
Xamarin/NumericUpDown/Getting-Started.md
Xamarin/NumericUpDown/Localization.md
Xamarin/NumericUpDown/Number-Formatting.md
Xamarin/Parallax-View/Customization.md
Xamarin/Parallax-View/GettingStarted.md
Xamarin/Pdf-Viewer/Designing-a-Custom-Toolbar.md

Hello,
I have worked on the links with redirects.
Regards,
Beryl.

SEO-176113-Xamarin-Page-With-Redirect1

---

Xamarin/Pdf-Viewer/Select-And-Copy-Text.md

855497: Publish UG documentation for TextSelectionMenuItemClicked event.

855497: Publish UG documentation for TextSelectionMenuItemClicked event.

---

Xamarin/Chat/Accessibility.md
Xamarin/Chat/Getting-started.md
Xamarin/Chat/Scrolling.md
Xamarin/CheckBox/Getting-Started.md
Xamarin/CheckBox/Visual-Customization.md
Xamarin/Chips/Customization.md
Xamarin/Chips/DataTemplateSelector.md
Xamarin/Chips/Events.md
Xamarin/Chips/Getting-Started.md
Xamarin/Chips/Populating-chips-item.md
Xamarin/Chips/Types.md

Have made changes on the redirect links. Please review.
Thanks.
Regards,
Edith.

SEO-176062-xamarin-UG-redirect

---

Xamarin/DataGrid/Load-More.md
Xamarin/DataGrid/Localization.md
Xamarin/DataGrid/Paging.md
Xamarin/DataGrid/Row-Height-Customization.md
Xamarin/DataGrid/RowDragAndDrop.md
Xamarin/DataGrid/Scrolling.md
Xamarin/DataGrid/Selection.md
Xamarin/DataGrid/Sorting.md
Xamarin/DataGrid/Stacked-Headers.md
Xamarin/DataGrid/Unbound-Row.md

Have made changes on the redirect links. Please review.
Thanks.
Regards,
Edith.

SEO-176062-xamarin-UG-redirects-links

---

Xamarin/Charts/legend.md
Xamarin/DataGrid/Selection.md
Xamarin/Tabbed-View/Getting-Started.md

HI @MallikaRK ,
Please review the changes.
Thanks.
Regards,
Edith.

SEO-176496-xamarin-page-with-redirect-links

---

Xamarin/Calendar/Right-to-left.md

Have worked on Xamarin Page with Redirect links.
Regards,
Yvone.

SEO-178567 Xamarin Page with Redirect

---

Xamarin/Scheduler/right-to-left.md

Hello,
I have worked on links with redirects.
Kind regards,
Beryl.

SEO-178943-WPF-Redirect-Links

---

Xamarin/DataForm/Editing.md
Xamarin/DataGrid/Stacked-Headers.md

Please review the redirect link changes made
Thanks.
Regards,
Edith.

SEO-178901-Xamarin-page-with-redirect

---

Xamarin/DataGrid/Conditional-Styles.md
Xamarin/Pdf-Viewer/Touch-Interaction-Events.md
Xamarin/Popup/Popup-Animations.md
Xamarin/Scheduler/WeekView.md

Please review the redirect link changes made
Thanks.
Regards,
Edith.

SEO-178901-xamarin-ug-page-with-redirect-links

---

Xamarin/ListView/ViewAppearance.md

Hi @MallikaRK
Kindly review my PR in page with redirect UG help under Xamarin.
Regards.
Dickson J

SE0-174654-Xamarin-Page-With-Redirect-UG-Help

---

Xamarin/DataGrid/Row-Height-Customization.md
Xamarin/Text-Input-Layout/Container-Type.md

Hi @MallikaRK,
please review the changes made.
Thanks.
Regards,
Edith.

SEO-178901-Xamarin-ug-page-with-redirect-links(1)

---

Xamarin/Segmented-Control/Dealing-with-selection-changed.md

Hello,
I have worked on links with redirects.
Regards,
Beryl.

SEO-179239-Redirect-Links-Xamarin

---

Xamarin/Circular-Gauge/scales.md
Xamarin/ComboBox/Getting-Started.md
Xamarin/Maps/MapsProvider.md
Xamarin/Maps/Sublayer.md
Xamarin/Popup/getting-started.md

Kindly review the changes.
Regards,
Edith.

SEO-180458-Xamarin-ug-redirect-links

---

Xamarin/TreeView/load-on-demand.md

Kindly review the PR changes.
Regards,
Edith.

SEO-180844-xamarin-page-with-redirect

---

Xamarin/DataGrid/Column-Sizer.md
Xamarin/DataGrid/Load-More.md
Xamarin/DataGrid/Selection.md
Xamarin/DataGrid/Styles.md
Xamarin/Maps/MapsProvider.md
Xamarin/Rich-Text-Editor/Basic-Features.md
Xamarin/Rich-Text-Editor/Right-to-left.md

Hello,
I have worked on links with redirects.
Regards,
Beryl.

SEO-178281-Links-With-Redirects-Xamarin

---

Xamarin/DateTime-Range-Navigator/rangenavigator.md

Hi @Yvone-Atieno,
Kindly review my PR
Regards,
Faith

Seo  181194 xamarin.docs page with redirect link

---

Xamarin/DataGrid/ColumnDragAndDrop.md
Xamarin/DataGrid/Columns.md
Xamarin/DataGrid/Export-To-Excel.md
Xamarin/DataGrid/Export-To-PDF.md
Xamarin/DataGrid/Load-More.md

Hi @MallikaRK,
Worked on Xamarin-Changes.
Regards,
Sharly A.

SEO-181938-Xamarin -changes

---

Xamarin/Maps/Legend.md
Xamarin/Maps/ShapeType.md
Xamarin/TreeView/right-to-left.md

Hi @gowthamanthavasiyappan ,
Kindly review the referring links issue fixed.
Thanks.
Regards,
Edith.

SEO-180844-xamarin-refering-page

---

Xamarin/Charts/Getting-Started.md
Xamarin/Themes/Themes.md

Have worked on changing title and description in Xamarin controls, please review.
Regards,
Yvone.

SEO-181951 Xamarin Title Identical

---

Xamarin/Parallax-View/Customization.md

Have worked on Missing H1, please review.
Regards,
Yvone.

SEO-183463 Xamarin Missing H1

---

Xamarin/AutoComplete/Populating-Data.md
Xamarin/Picker/Overview.md
Xamarin/Rating/Getting-Started.md
Xamarin/Scheduler/overview.md
Xamarin/System-Requirements.md

Hi @gowthamanthavasiyappan 
Kindly Review my PR below.
Regards
Dickson J

SEO-174654-Xamarine-Page-With-Redirect-One

---

Xamarin/AutoComplete/Overview.md
Xamarin/DataGrid/Overview.md

Have modified title, H1 and description, please review.
Regards,
Yvone.

SEO-184192 Xamarin Page with Redirect

---

Xamarin/Visual-Studio-Integration/Check-for-Updates.md
Xamarin/Visual-Studio-Integration/Create-Project.md
Xamarin/Visual-Studio-Integration/Download-and-Installation.md
Xamarin/Visual-Studio-Integration/Essential-UI-Kit.md
Xamarin/Visual-Studio-Integration/Toolbox-Control.md

Resolve conflict

---

Xamarin/DataGrid/Row-Height-Customization.md

-- | --
|Task Category | Site Audit|
|Content Task Link/Mail Screenshot | NA |
|Hotfix | https://github.com/syncfusion-content/xamarin-docs/pull/926|
|Ticket/Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/185650|
|Work link | https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7b77F3CB04-376A-4012-82C2-C311813783B6%7d&file=Faith.xlsx&action=default&mobileredirect=true&wdsle=0|
Changes made | Reason for change
-- | --
| Http to Https| To increase page performance |

185650-Http-to-Https-Row-height-customirization

---

Xamarin/TreeView/Getting-started.md

-- | --
|Task Category |  Coverage issues|
|Content Task Link/Mail Screenshot | NA |
|Hotfix | https://github.com/syncfusion-content/xamarin-docs/pull/929|
|Ticket/Task link |  https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/185658/|
|Work link | https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7BD059EAE3-DA11-4570-A59B-D252A95C9DFD%7D&file=Faith.xlsx&action=default&mobileredirect=true&wdsle=0|
Changes made | Reason for change
-- | --
| Page with redirect| To increase page performance |

185658-Ej2-XamarinForms-Treeview

---

xamarin-toc.html

Task - https://dev.azure.com/Syncfusion-Infrastructure/Install/_workitems/edit/187726/

187726 - Syncfusion License Validation Page Location Updated - Live

---

Xamarin/DataGrid/Data-Binding.md

-- | --
|Task Category | Coverage Issues page with redirect links|
|Content Task Link/Mail Screenshot |NA|
|Hotfix |https://github.com/syncfusion-content/xamarin-docs/pull/1048 |
|Ticket/Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/195602|
|Work link | https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/doc2.aspx?sourcedoc=%7B24695E6D-B9D5-4F5A-A3BE-6D83ACE1AE3C%7D&file=Help%20Page%20with%20Redirect.xlsx&action=default&mobileredirect=true&wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1736940295182&web=1&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiI0OS8yNDEyMDEwMDIxMyIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D|
Changes Made | Reason for change |
|-- | …

SEO-195602-Xamarin.Form-DataGrid-Page-with-redirect-links

---

Xamarin/DataGrid/Data-Binding.md

#Description.
- Have added link for source collection changed

Added the hyperlink for SourceCollectionChanged event in Xamarin DataGrid UG

---

Xamarin/Image-Editor/Serialization.md

Xamarin unwanted link removed in ImageEditor UG on Serialization topic.

932495-[Dev] Xamarin ImageEditor unwanted link removed

---

Xamarin/DataForm/Working-with-DataForm.md

Hi @MallikaRK 
-- | --
|Task Category |The title tag contains additional tags.|
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/201392/|
Changes Made | Reason for change |
|-- | -- |
|Change the title tag contains additional tags. | delete the <sup>&reg;</sup> | 
Regards, 
Asha

seo-201424-xamarin-meta-title-change-hotfix

---

Xamarin/Introduction/Overview.md

| Title | Description |
| -------- | -------- |
|**Task Link**|[https://dev.azure.com/Syncfusion-Infrastructure/Install/_workitems/edit/203452|](/%7C)](https://dev.azure.com/Syncfusion-Infrastructure/Install/_workitems/edit/203452%7C%5d(/%7C))
|**Analysis and design**|-|
|**Solution description**|we have to add banner content for xamarin platforms.the content is : "With the 2025 Volume 3 release, support for Xamarin platforms will be discontinued. We recommend migrating to .NET MAUI to continue receiving updates and support."|
|**Output screenshots**|<img width="1848" height="562" alt="image" src="https://github.com/user-attachments/assets/171e5ec3-8a63-4883-b5f1-2a72e1c942f0" />|
|**Test cases**||
|**Testbed sample location**|Tested Locally and Ensured.|
|**Additional …

changes to add the banner content

---

xamarin-toc.html

-- | --
|Task Category |Removed control list.|
|Ticket/Task link| https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/976406|
|Share point | -|
Changes Made | Reason for change |
|-- | -- |
|Removed Excel list | Removed Excel list as per instruction |

976406: Remove Excel list from Xamarin
